http:
  port: 8081
apiEndpoints:
  api:
    host: 135.181.150.234
    paths: [
      '/products',
      '/products*',
      '/categories',
      '/categories/*',
      '/products/search',
      '/products/category/*',
      '/products/:id'
    ]
serviceEndpoints:
  httpbin:
    url: 'http://135.181.150.234:7000/v1'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - request-transformer
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
